In [1]:
import torch
import torch.nn as nn

In [2]:
x = torch.tensor(
    [
        [0.0,0.0],
        [0.0,1.0],
        [1.0,0.0],
        [1.0,1.0],
    ]
)

y = torch.tensor(
    [
        [0.0],
        [0.0],
        [0.0],
        [1.0]
    ]
)

In [3]:
print(type(x))

<class 'torch.Tensor'>


In [5]:
class Perceptron(nn.Module):
    def __init__(self,input_size):
        super(Perceptron, self).__init__()

        self.weight = nn.Parameter(torch.randn(input_size))
        self.bias = nn.Parameter(torch.zeros(1))
    def forward(self, x):
        z = x @ self.weight + self.bias

        y_pred = torch.sigmoid(z)
        return y_pred

In [6]:
model = Perceptron(input_size=2)

In [9]:
torch.manual_seed(42)
x = torch.randn(2)
x

tensor([0.3367, 0.1288])

In [11]:
y_pred = model(x)
y_pred

tensor([0.5406], grad_fn=<SigmoidBackward0>)

In [12]:
print(*model.parameters())

Parameter containing:
tensor([ 1.0912, -1.5886], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)


In [14]:
criterion = nn.BCELoss()

optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)


BCELoss()