In [ ]:
print("Hello World")

In [ ]:
import numpy as np
np.__version__

In [ ]:
"""
Property: dtype,shape,ndim
"""
my_array = np.array(
    [1,2,3]
)
print(my_array)
print(type(my_array))
print(my_array.dtype)  #data type
print(my_array.shape)  #shap
print(my_array.ndim)   #dimension

In [ ]:
zero_array = np.zeros(
    shape=(5,)
)
print(zero_array)

In [ ]:
one_array = np.ones(
    shape=(5,2),
    dtype=int
)
print(one_array)

In [ ]:
num_array = np.full(
    shape=(5,2),
    fill_value=2,
    dtype=int
)
print(num_array)

In [ ]:
"""
Identity Matrix
[1 0 0]
[0 1 0]
[0 0 1]
"""

id_matrix = np.eye(4)
id_matrix

In [ ]:
np.empty(shape=4)

In [ ]:
'''Type Cast'''

print(id_matrix.dtype)
type_cast = id_matrix.astype(int)
print(type_cast.dtype)

In [ ]:
# Sequential Array

np.arange(start=0, stop=10, step=2)

In [ ]:
np.linspace(start=0, stop=100, num=10)         #Same Distance

In [ ]:
"""
Numpy array dimensions

scalar -> 0D
vector -> 1D
matrix -> 2D
tensor -> xD where x > 2

tensor is unit data type of Pytorch and Tensorflow

"""
numpy_0d = np.array(42)
print(numpy_0d, numpy_0d.ndim)

numpy_1d = np.array(
    [1,2,4,5]
)
print(numpy_1d, numpy_1d.ndim)

numpy_2d = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(numpy_2d, numpy_2d.ndim)

In [ ]:
"""Indexing
Non-Negative indexing
Negative indexing
"""

arr = np.array([1,2,3,4,5])
print(arr[2])
print(arr[-3])

arr2d = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]]
)
print(arr2d[2,1])
print(arr2d[-1,-2])

In [ ]:
arr[1:4:1]

In [ ]:
arrr = np.array([1,2,3,4,5])

for val in arrr:
    print(val)

In [ ]:
for i in range(len(arrr)):
    print(arrr[i])

In [ ]:
for index, val in enumerate(arrr):
    print(f"index = {index}: value = {val}")

In [ ]:
my_2d = np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15]
    ]
)
print(my_2d.shape)
my_2d.reshape(5,3)

In [ ]:
"""Reshaping with -1"""

a = np.zeros(shape=(3,4,2,2))
print(a)
print(a.reshape(2,2,-1))


In [ ]:
"""Sort"""

probability =  np.array(
    [.3,.6,.3,.1]
)
np.sort(probability)
np.sort(probability)[::-1]

In [ ]:
'''Argmax Argmin'''
print(np.argmax(probability))
print(np.argmin(probability))

In [ ]:
"""Split"""
arr = np.array([9,1,2,3,4,8,5,6])

new_arr = np.split(arr, 2)
print(new_arr)

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
np.dot(arr1, arr2)

In [ ]:
arr3 = np.array(
    [[1,2,3,4,5],
    [4,5,6,7,8]]
)
print(arr3.shape)
print(arr3.T)

In [ ]:
'''
std = sqrt((n1-mean)^2 + (n2-mean)^2)/(n-1))
'''

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

In [ ]:
'''Numpy Fileter
Option 1 -> Boolean Mask
'''

my_arr = np.array([1,2,3,4,5])

filer_mask = [True,False,True,False,False]
print(my_arr[filer_mask])

In [ ]:
""" Option2 -> Conditional """

filer_mask = (my_arr % 2 == 1)
print(filer_mask)
print(my_arr[filer_mask])

In [ ]:
'''Option3 -> indices'''
indices = [1,2]
print(my_arr[indices])

In [ ]:
'''Custom Filer Method'''

def my_filer(X):
    if X % 2 == 0:
        return False
    return True

filter_iterable = filter(my_filer, my_arr)
myfiter_arr = np.array(
    list(filter_iterable)
)
myfiter_arr

In [ ]:
"""
Vectorization

in normal array if we want to add 7 we need to go to each index and add 7
for i in arr:
    i = i + 7

in vectorization

1       2       3       4       5
7       7       7       7       7
=8      9       10      11      12

done at a time (1 iteration)

"""

Broadcasting

In [ ]:
""" Converting a lower shape to higher shape for vectorization
old shap = (2,)
new shape = (4,2)

condition:

two dimensions are compatible (Right -> left) when:
    they are equal
    or one of them is 1
 """



w = np.array(
    [1,2]
)
x = np.array(
    [[3,4],
     [5,6],
     [7,8],
     [9,10]
     ]
)
print(w*x)

Numpy Axis

In [ ]:
'''
First Dimension = 0
Second Dimension = 1
Nth Dimension = N-1

Aggregation function: sum,min,max, median
'''

In [ ]:
ax = np.zeros(
    shape=(2,3,3),
    dtype=int
)
ax

In [ ]:
a = np.array(
    [
        [1,-3,7],
        [3,4,-1]
        # [1,1,3]
    ]
)
print(np.sum(a,axis=1))


In [ ]:
'''For 1D axis -> 0 one axis
For 2D axis -> 0 column
axis -> 1 row'''

In [25]:
"""Random"""

b = np.random.randint(5,size=(2,4))
b#[0,1]

array([[3, 4, 3, 4],
       [4, 1, 1, 2]])

In [29]:
np.random.shuffle(b)
print(b)

[[4 1 1 2]
 [3 4 3 4]]
