In [ ]:
print("Hello World")

In [ ]:
import numpy as np
np.__version__

In [ ]:
"""
Property: dtype,shape,ndim
"""
my_array = np.array(
    [1,2,3]
)
print(my_array)
print(type(my_array))
print(my_array.dtype)  #data type
print(my_array.shape)  #shap
print(my_array.ndim)   #dimension

In [ ]:
zero_array = np.zeros(
    shape=(5,)
)
print(zero_array)

In [ ]:
one_array = np.ones(
    shape=(5,2),
    dtype=int
)
print(one_array)

In [ ]:
num_array = np.full(
    shape=(5,2),
    fill_value=2,
    dtype=int
)
print(num_array)

In [ ]:
"""
Identity Matrix
[1 0 0]
[0 1 0]
[0 0 1]
"""

id_matrix = np.eye(4)
id_matrix

In [ ]:
np.empty(shape=4)

In [ ]:
'''Type Cast'''

print(id_matrix.dtype)
type_cast = id_matrix.astype(int)
print(type_cast.dtype)

In [ ]:
# Sequential Array

np.arange(start=0, stop=10, step=2)

In [ ]:
np.linspace(start=0, stop=100, num=10)         #Same Distance

In [ ]:
"""
Numpy array dimensions

scalar -> 0D
vector -> 1D
matrix -> 2D
tensor -> xD where x > 2

tensor is unit data type of Pytorch and Tensorflow

"""
numpy_0d = np.array(42)
print(numpy_0d, numpy_0d.ndim)

numpy_1d = np.array(
    [1,2,4,5]
)
print(numpy_1d, numpy_1d.ndim)

numpy_2d = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(numpy_2d, numpy_2d.ndim)

In [ ]:
"""Indexing
Non-Negative indexing
Negative indexing
"""

arr = np.array([1,2,3,4,5])
print(arr[2])
print(arr[-3])

arr2d = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]]
)
print(arr2d[2,1])
print(arr2d[-1,-2])

In [ ]:
arr[1:4:1]